theme: jekyll-theme-tactile
title: Vimspector
description: A multi-language debugging plugin for Vim
show_downloads: "true"
github:
  public: true
  owner_url: https://github.com/puremourning/vimspector
  tar_url: https://github.com/puremourning/vimspector/releases
  zip_url: https://github.com/puremourning/vimspector/releases
